### PR TITLE
Added GetCategories method

### PR DESCRIPTION
**Pull request by tekguy**
Created a get categories method

### CODE REVIEW

**Comment by abrudtkuhl** [comment]
Awesome thanks @tekguy

**Comment by abrudtkuhl** [comment]
@tekguy appears to be some merge conflicts. can you check it out? Not sure if it's from another PR today or not.

**Comment by tekguy** [comment]
@abrudtkuhl should be interesting, i have to figure out how to do this, i don't use github often i will take a look :)

**Comment by tekguy** [comment]
@abrudtkuhl Ok, I was able to resolve the merge conflicts, I can also build the project. Thanks!

**Comment by abrudtkuhl** [comment]
awesome nice work!

--  
Andy Brudtkuhl
@abrudtkuhl (http://twitter.com/abrudtkuhl)

**Comment by tayfunyasar** [comment]
Will you include this? Still waiting.

**Comment by abrudtkuhl** [comment]
Yes sorry! Pulled in now

**Pull request merged**
